# Secret content can be stored publicly as the content is encrypted with a private key which is only available in my local machine
apiVersion: v1
kind: Secret
metadata:
    name: age-key
    namespace: argocd
data:
    keys.txt: ENC[AES256_GCM,data:eyin7X2U1G4Yn/fnFdK+yCnRc3+Udi+wzRp54HiCjG+zrvvZKdDe4LjIPUiWVWWWOaYWf5VKb5m3kvABgdN/ppep3R9qzfx+yXII3+/x2vixkLyNa7HNBkUBentik0aultftiw==,iv:5765Yyg7+Rp+3PfiMCW6EyOX4FX7o/JklhNXCfY9v3s=,tag:nORVAxN4R0ArMqc7VDEwdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1849p3tf6q843d54gcpv7xycpy27d48d5a6tc2dan6mt8vdt4t4rqxlnr39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MWhqZzRTbm5MT0tuTk8y
            ai9zRHVHa1pLQWR6U1JVL0lEV0M5Y2gzeTNRCmJsNmRWNSt4SkVja3JucXRiM01J
            L0ZKc1hERkVVTERmUDVVRFM1K3ZLdmsKLS0tIHZSUWJ0UWxSMkFLN2dlVVFOc0hn
            bWVyMGdBRjc0UkN1c0dKSm9OREloYmsK2980nRZB8aEOp3fCrbOvT/C6mEOBm9L4
            nAhoj0RMfETLuqRMafKpWpG9YKfdWdhQlN7oHUd9HgQajYu3F+Wsug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-18T18:28:00Z"
    mac: ENC[AES256_GCM,data:2WG7PtLY9E/v8oL4nrFHaBZ3+dqNB+wvCjeZcCRsDPrCKSOjMuDGHr9JsVcHeWsG2WPqIleIrXW+47gECNXpoxzzkv4sKK4ZyLUKCXgeXtLHbMs9ei3tPfP6sX+PqeTlcA1yhZoGVp77x7M6BbRLHSxnF/iRHdBTn/AKaUzn7gY=,iv:l1ppCTxxQC6UWqGhVYVKxoC7HCIoEAawO1YCJhskYls=,tag:UxdTBUYZNdUpx3GYsTax4g==,type:str]
    pgp: []
    encrypted_regex: ^(secret|data|stringData)$
    version: 3.7.1
