---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-helm
spec:
  project: default
  source:
    repoURL: https://github.com/dharapvj/argocd-demo
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
        - secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raw-k8s
spec:
  destination:
    namespace: hello-world
    server: 'https://kubernetes.default.svc'
  source:
    path: raw-k8s/
    repoURL: 'https://github.com/dharapvj/argocd-demo'
    targetRevision: HEAD
    plugin:
      name: sopsDecrypt
  project: default
  syncPolicy:
    automated: null
