apiVersion: v1
#mysecret: secret_value
data:
    mysecret: ENC[AES256_GCM,data:+TIDSAE4j/f+hGnpFbxCQA==,iv:SuTHmcSorkm10M7Q7h2NbS2sNH5OmJAem/D/LYCw/vo=,tag:iVuVx4TJR2x+JNGhUWUYWw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: demo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age188h9jq84dl4spnfc5uev7swpcv7sut6y33aqx328yu4rmf7d5s3suvrcdh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNEZlMFJoSVpGR1JKVVEx
            SStidkxNTVpIakgrZnBsSHFyeC9lblBjaldVCjdKdHprdWk1YmlYOU5JQ0c1M2ow
            Mk5Zd2krakFEcDVYMXJmVzdMZXdmK1UKLS0tIG1TVEsvRGswT3pFMXVjWUZEL1Mw
            SHZJQnp2bzR2eitoVEY5VTNOTGMrNU0Kv+l5rJQnfG9DjDiOvhpWrv1sAiQmfMCt
            MThzSdcZpgyV5QW4X2Pp7800ATOcnbXKo9rLdnEfwD+rnD8Adoe3gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-14T17:15:25Z"
    mac: ENC[AES256_GCM,data:IhI80XVKlq0/61FIZnbCkHRy2ti4ZRq3+/HKnNcLT1/wgu6dGW9fANb4Ql9qEu7nu6XARxgp4NYGPTfw35caivnd2JiLElrXfxBmfWjs9BNAKVejYF5+kiqSZXCw/MEb2tb1mVxGWkwypAjXz3xeKt5KdgvR/8BPo9LMcrpdaaU=,iv:gaCwlFCfIBvEAMvvdApogD6LTnX4EqZpQHP7uNQmJHc=,tag:bwi1jzSmMis4d0Z+XPpj8w==,type:str]
    pgp: []
    encrypted_regex: ^(secret|data|stringData)$
    version: 3.7.1
