apiVersion: v1
#mysecret: secret_value
data:
    mysecret: ENC[AES256_GCM,data:jPbhDOkkk6JlBZYRgCFiDA==,iv:Z94WaFqYpnUQbVG82209P3rHlQjE4w7WhXctvubtIOg=,tag:VnXgmpOHUlc2lZvXG21z2g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: demo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age188h9jq84dl4spnfc5uev7swpcv7sut6y33aqx328yu4rmf7d5s3suvrcdh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNEZlMFJoSVpGR1JKVVEx
            SStidkxNTVpIakgrZnBsSHFyeC9lblBjaldVCjdKdHprdWk1YmlYOU5JQ0c1M2ow
            Mk5Zd2krakFEcDVYMXJmVzdMZXdmK1UKLS0tIG1TVEsvRGswT3pFMXVjWUZEL1Mw
            SHZJQnp2bzR2eitoVEY5VTNOTGMrNU0Kv+l5rJQnfG9DjDiOvhpWrv1sAiQmfMCt
            MThzSdcZpgyV5QW4X2Pp7800ATOcnbXKo9rLdnEfwD+rnD8Adoe3gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-17T10:57:36Z"
    mac: ENC[AES256_GCM,data:fuCUxZh3E1xVZXs/X3Kfq+bXZaKxXzJ8NBawXOPnKWtpjgu7IMxXiK+FtPMlfFdaUqQw+CHjLbykqiR/VbAVaGEtbzRZHwZ1ZaLhHnD0JESkHxtXM0W+P+Mj9/nnM5k9Ske5EJakwmgbBdoR03iETSodhsXpls2UItw2d4FtoII=,iv:7WFvAc4gatXGUDmDImU3KYnsnaxoFcEPkznvR0s78ug=,tag:J3Wq47RyVX0TyV07a+hS4A==,type:str]
    pgp: []
    encrypted_regex: ^(secret|data|stringData)$
    version: 3.7.1
